### ISSUE TITLE
navigator.clipboard undefined

### ISSUE THREAD

**Issue by ihfazhillah** [gattigaga/quorts#1]
Hi, i've tried your awesome google chrome extension. But i found problem when i tried to copy a quoted text. 
I check console, and i found that `navigator.clipboard` 

i use Version 65.0.3325.162 (Official Build) (64-bit) in debian.

thanks.

**Comment by gattigaga** [comment]
navigator.clipboard is supported for Chrome 66+. Currently I don't find good alternative to make clipboard work on older Chrome version.

**Comment by ihfazhillah** [comment]
Hi, why not to use https://clipboardjs.com/ or another approach like in this discussion https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
